### ISSUE TITLE
Explore Code2Vec parser

### ISSUE THREAD

**Issue by jonbriem** [pdrapoport/ML4SA#4]
Look into how Python works with code2vec
Make sure we are able to go from code to AST and vice versa.
Find a way to trim the tree down to single functions only

**Comment by hsellik** [comment]
There is ASTMiner (https://github.com/vovak/astminer/tree/master/astminer-cli) which automatically extracts methods (ignores other code in class) and produces 4 files:

node_types.csv
path_contexts.csv
paths.csv
tokens.csv

- path_contexts.csv is in the following format:
    `method|name 2,5,3 number,number,number ...,...,...`
    Where the first (2) and the third number (3) are from tokens.csv. The middle number (5) is from the 
    paths.csv file.

 - tokens.csv contains entries such as 
    `id,token`
     `5,print` where 5 is id and print a token

- paths.csv
    `id,path`
    `35,32 27 28 21 22` the numbers after id represent node types and can be found in node_types.csv

- node_types.csv
    `id,node_type`
    `17,NEWLINE DOWN`
    `18,CLOSE_PAREN UP`

**Comment by hsellik** [comment]
The problem I have with this approach:

- Preprocessing new set of data will produce different tokens. Meaning that if we use number representations of tokens as in path_contexts.csv, they would be useless. We would need to use the string representations so the training and later testing data would be the same, I guess?
